services:
  # Auth Service (Dev Mode)
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile.dev
    volumes:
      - ./services/auth-service:/app/services/auth-service
      - ./pkg:/app/pkg
    environment:
      - GO_ENV=development
      - DEBUG=true
    ports:
      - "9000:8080" # Expose port for direct access
      - "40000:40000" # Delve debugger port

  # User Service (Dev Mode)
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile.dev
    volumes:
      - ./services/user-service:/app/services/user-service
      - ./pkg:/app/pkg
    environment:
      - GO_ENV=development
      - DEBUG=true
    ports:
      - "9001:8080" # Expose port for direct access
      - "40001:40000" # Delve debugger port

  # Gateway (Dev Mode)
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile.dev
    volumes:
      - ./gateway:/app/gateway
      - ./pkg:/app/pkg
    environment:
      - GO_ENV=development
      - DEBUG=true
    ports:
      - "8080:8080"
      - "40002:40000" # Delve debugger port
