services:
  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"
      - "8222:8222"

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats
      - user-service
