#!/bin/bash

# setup-env-dev.sh
# Script to set up .env.dev files for all services

set -e

SERVICES=("auth-service" "user-service" "entity-service" "incident-service" "location-service" "monitoring-service" "notification-service" "chat-service")

echo "Setting up .env.dev files for all services..."

# Create .env.dev for each service
for service in "${SERVICES[@]}"; do
    service_dir="services/${service}"
    env_file="${service_dir}/.env.dev"
    
    if [ ! -d "$service_dir" ]; then
        echo "Warning: Service directory $service_dir does not exist, skipping..."
        continue
    fi
    
    if [ -f "$env_file" ]; then
        echo "✓ $env_file already exists"
        continue
    fi
    
    echo "Creating $env_file..."
    
    # Create basic .env.dev file for each service
    cat > "$env_file" << EOF
# ${service} Development Environment Variables
# Generated by setup-env-dev.sh

# Service Configuration
$(echo "${service}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')_NAME=${service}
$(echo "${service}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')_VERSION=1.0.0-dev
$(echo "${service}" | tr '[:lower:]' '[:upper:]' | tr '-' '_')_PORT=8080

# Database Configuration (for local development)
DB_NAME=$(echo "${service}" | tr '-' '_')
DB_HOST=localhost
DB_PORT=3306
DB_USER=appuser
DB_PASSWORD=apppassword

# NATS Configuration (for local development)
NATS_URL=nats://localhost:4222

# Development-specific
GO_ENV=development
DEBUG=true
LOG_LEVEL=debug
EOF
    
    echo "✓ Created $env_file"
done

# Create gateway .env.dev
gateway_env="gateway/.env.dev"
if [ ! -f "$gateway_env" ]; then
    echo "Creating $gateway_env..."
    cat > "$gateway_env" << EOF
# Gateway Development Environment Variables
# Generated by setup-env-dev.sh

# Service Configuration
GATEWAY_NAME=api-gateway
GATEWAY_VERSION=1.0.0-dev
PORT=8080

# NATS Configuration (for local development)
NATS_URL=nats://localhost:4222

# Gateway-specific Configuration
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8080,http://localhost:5173
RATE_LIMIT=1000

# Development-specific
GO_ENV=development
DEBUG=true
LOG_LEVEL=debug
EOF
    echo "✓ Created $gateway_env"
else
    echo "✓ $gateway_env already exists"
fi

echo ""
echo "✅ Setup complete!"
echo ""
echo "📝 Next steps:"
echo "1. Review and customize each .env.dev file for your specific needs"
echo "2. Update service-specific configuration in each file"
echo "3. For local development: make infra-up && make run-{service-name}"
echo "4. For Docker development: make dev-up"
echo ""
echo "📁 Created environment files:"
for service in "${SERVICES[@]}"; do
    if [ -f "services/${service}/.env.dev" ]; then
        echo "   - services/${service}/.env.dev"
    fi
done
if [ -f "gateway/.env.dev" ]; then
    echo "   - gateway/.env.dev"
fi
echo ""
echo "🔧 Environment file priority (highest to lowest):"
echo "   1. Service-specific .env.dev (services/{service}/.env.dev)"
echo "   2. Root .env file"
echo "   3. Default values in docker-compose files"