// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/entities/entities.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_pkg_proto_entities_entities_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entity) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Entity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AreaId        string                 `protobuf:"bytes,4,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_pkg_proto_entities_entities_proto_rawDescGZIP(), []int{1}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Subscription) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Subscription) GetAreaId() string {
	if x != nil {
		return x.AreaId
	}
	return ""
}

func (x *Subscription) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityRequest) Reset() {
	*x = GetEntityRequest{}
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityRequest) ProtoMessage() {}

func (x *GetEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityRequest.ProtoReflect.Descriptor instead.
func (*GetEntityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_entities_entities_proto_rawDescGZIP(), []int{2}
}

func (x *GetEntityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntityResponse) Reset() {
	*x = GetEntityResponse{}
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntityResponse) ProtoMessage() {}

func (x *GetEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntityResponse.ProtoReflect.Descriptor instead.
func (*GetEntityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_entities_entities_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntityResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type SearchEntitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEntitiesRequest) Reset() {
	*x = SearchEntitiesRequest{}
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEntitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEntitiesRequest) ProtoMessage() {}

func (x *SearchEntitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEntitiesRequest.ProtoReflect.Descriptor instead.
func (*SearchEntitiesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_entities_entities_proto_rawDescGZIP(), []int{4}
}

func (x *SearchEntitiesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchEntitiesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchEntitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchEntitiesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEntitiesResponse) Reset() {
	*x = SearchEntitiesResponse{}
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEntitiesResponse) ProtoMessage() {}

func (x *SearchEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEntitiesResponse.ProtoReflect.Descriptor instead.
func (*SearchEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_entities_entities_proto_rawDescGZIP(), []int{5}
}

func (x *SearchEntitiesResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SearchEntitiesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetEntitySubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitySubscriptionsRequest) Reset() {
	*x = GetEntitySubscriptionsRequest{}
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitySubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitySubscriptionsRequest) ProtoMessage() {}

func (x *GetEntitySubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitySubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetEntitySubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_entities_entities_proto_rawDescGZIP(), []int{6}
}

func (x *GetEntitySubscriptionsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type GetEntitySubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitySubscriptionsResponse) Reset() {
	*x = GetEntitySubscriptionsResponse{}
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitySubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitySubscriptionsResponse) ProtoMessage() {}

func (x *GetEntitySubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_entities_entities_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitySubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetEntitySubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_entities_entities_proto_rawDescGZIP(), []int{7}
}

func (x *GetEntitySubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_pkg_proto_entities_entities_proto protoreflect.FileDescriptor

const file_pkg_proto_entities_entities_proto_rawDesc = "" +
	"\n" +
	"!pkg/proto/entities/entities.proto\x12\bentities\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x02\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12@\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2 .entities.Entity.AttributesEntryR\n" +
	"attributes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x17\n" +
	"\aarea_id\x18\x04 \x01(\tR\x06areaId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\"\n" +
	"\x10GetEntityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x11GetEntityResponse\x12(\n" +
	"\x06entity\x18\x01 \x01(\v2\x10.entities.EntityR\x06entity\"o\n" +
	"\x15SearchEntitiesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\\\n" +
	"\x16SearchEntitiesResponse\x12,\n" +
	"\bentities\x18\x01 \x03(\v2\x10.entities.EntityR\bentities\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"<\n" +
	"\x1dGetEntitySubscriptionsRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"^\n" +
	"\x1eGetEntitySubscriptionsResponse\x12<\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x16.entities.SubscriptionR\rsubscriptions2\x97\x02\n" +
	"\rEntityService\x12D\n" +
	"\tGetEntity\x12\x1a.entities.GetEntityRequest\x1a\x1b.entities.GetEntityResponse\x12S\n" +
	"\x0eSearchEntities\x12\x1f.entities.SearchEntitiesRequest\x1a .entities.SearchEntitiesResponse\x12k\n" +
	"\x16GetEntitySubscriptions\x12'.entities.GetEntitySubscriptionsRequest\x1a(.entities.GetEntitySubscriptionsResponseB*Z(github.com/0xsj/fn-go/pkg/proto/entitiesb\x06proto3"

var (
	file_pkg_proto_entities_entities_proto_rawDescOnce sync.Once
	file_pkg_proto_entities_entities_proto_rawDescData []byte
)

func file_pkg_proto_entities_entities_proto_rawDescGZIP() []byte {
	file_pkg_proto_entities_entities_proto_rawDescOnce.Do(func() {
		file_pkg_proto_entities_entities_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_entities_entities_proto_rawDesc), len(file_pkg_proto_entities_entities_proto_rawDesc)))
	})
	return file_pkg_proto_entities_entities_proto_rawDescData
}

var file_pkg_proto_entities_entities_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_entities_entities_proto_goTypes = []any{
	(*Entity)(nil),                         // 0: entities.Entity
	(*Subscription)(nil),                   // 1: entities.Subscription
	(*GetEntityRequest)(nil),               // 2: entities.GetEntityRequest
	(*GetEntityResponse)(nil),              // 3: entities.GetEntityResponse
	(*SearchEntitiesRequest)(nil),          // 4: entities.SearchEntitiesRequest
	(*SearchEntitiesResponse)(nil),         // 5: entities.SearchEntitiesResponse
	(*GetEntitySubscriptionsRequest)(nil),  // 6: entities.GetEntitySubscriptionsRequest
	(*GetEntitySubscriptionsResponse)(nil), // 7: entities.GetEntitySubscriptionsResponse
	nil,                                    // 8: entities.Entity.AttributesEntry
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
}
var file_pkg_proto_entities_entities_proto_depIdxs = []int32{
	8,  // 0: entities.Entity.attributes:type_name -> entities.Entity.AttributesEntry
	9,  // 1: entities.Entity.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: entities.Entity.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: entities.Subscription.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: entities.GetEntityResponse.entity:type_name -> entities.Entity
	0,  // 5: entities.SearchEntitiesResponse.entities:type_name -> entities.Entity
	1,  // 6: entities.GetEntitySubscriptionsResponse.subscriptions:type_name -> entities.Subscription
	2,  // 7: entities.EntityService.GetEntity:input_type -> entities.GetEntityRequest
	4,  // 8: entities.EntityService.SearchEntities:input_type -> entities.SearchEntitiesRequest
	6,  // 9: entities.EntityService.GetEntitySubscriptions:input_type -> entities.GetEntitySubscriptionsRequest
	3,  // 10: entities.EntityService.GetEntity:output_type -> entities.GetEntityResponse
	5,  // 11: entities.EntityService.SearchEntities:output_type -> entities.SearchEntitiesResponse
	7,  // 12: entities.EntityService.GetEntitySubscriptions:output_type -> entities.GetEntitySubscriptionsResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_proto_entities_entities_proto_init() }
func file_pkg_proto_entities_entities_proto_init() {
	if File_pkg_proto_entities_entities_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_entities_entities_proto_rawDesc), len(file_pkg_proto_entities_entities_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_entities_entities_proto_goTypes,
		DependencyIndexes: file_pkg_proto_entities_entities_proto_depIdxs,
		MessageInfos:      file_pkg_proto_entities_entities_proto_msgTypes,
	}.Build()
	File_pkg_proto_entities_entities_proto = out.File
	file_pkg_proto_entities_entities_proto_goTypes = nil
	file_pkg_proto_entities_entities_proto_depIdxs = nil
}
