global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/service-alerts.yml"
  - "rules/system-alerts.yml"

scrape_configs:
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:8080"]

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: "nats"
    static_configs:
      - targets: ["nats-exporter:9090"]
