// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/address/address.proto

package address

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address represents a physical address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Street        string                 `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode       string                 `protobuf:"bytes,5,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,7,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,8,opt,name=longitude,proto3" json:"longitude,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_pkg_proto_address_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_address_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_pkg_proto_address_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Address) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_pkg_proto_address_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_address_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_address_address_proto_rawDescGZIP(), []int{1}
}

func (x *GetAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressResponse) Reset() {
	*x = GetAddressResponse{}
	mi := &file_pkg_proto_address_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressResponse) ProtoMessage() {}

func (x *GetAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_address_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressResponse.ProtoReflect.Descriptor instead.
func (*GetAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_address_address_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type ValidateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode       string                 `protobuf:"bytes,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAddressRequest) Reset() {
	*x = ValidateAddressRequest{}
	mi := &file_pkg_proto_address_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAddressRequest) ProtoMessage() {}

func (x *ValidateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_address_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAddressRequest.ProtoReflect.Descriptor instead.
func (*ValidateAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_address_address_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *ValidateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *ValidateAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ValidateAddressRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *ValidateAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type ValidateAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAddressResponse) Reset() {
	*x = ValidateAddressResponse{}
	mi := &file_pkg_proto_address_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAddressResponse) ProtoMessage() {}

func (x *ValidateAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_address_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAddressResponse.ProtoReflect.Descriptor instead.
func (*ValidateAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_address_address_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateAddressResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GeocodeAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode       string                 `protobuf:"bytes,4,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeAddressRequest) Reset() {
	*x = GeocodeAddressRequest{}
	mi := &file_pkg_proto_address_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeAddressRequest) ProtoMessage() {}

func (x *GeocodeAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_address_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeAddressRequest.ProtoReflect.Descriptor instead.
func (*GeocodeAddressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_address_address_proto_rawDescGZIP(), []int{5}
}

func (x *GeocodeAddressRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *GeocodeAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GeocodeAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GeocodeAddressRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *GeocodeAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GeocodeAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeocodeAddressResponse) Reset() {
	*x = GeocodeAddressResponse{}
	mi := &file_pkg_proto_address_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeocodeAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeocodeAddressResponse) ProtoMessage() {}

func (x *GeocodeAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_address_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeocodeAddressResponse.ProtoReflect.Descriptor instead.
func (*GeocodeAddressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_address_address_proto_rawDescGZIP(), []int{6}
}

func (x *GeocodeAddressResponse) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeocodeAddressResponse) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeocodeAddressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GeocodeAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_proto_address_address_proto protoreflect.FileDescriptor

const file_pkg_proto_address_address_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/proto/address/address.proto\x12\aaddress\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x02\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06street\x18\x02 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\x05 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\a \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\b \x01(\x01R\tlongitude\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"#\n" +
	"\x11GetAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetAddressResponse\x12*\n" +
	"\aaddress\x18\x01 \x01(\v2\x10.address.AddressR\aaddress\"\x8f\x01\n" +
	"\x16ValidateAddressRequest\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"I\n" +
	"\x17ValidateAddressResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8e\x01\n" +
	"\x15GeocodeAddressRequest\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\x04 \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\"\x86\x01\n" +
	"\x16GeocodeAddressResponse\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\x80\x02\n" +
	"\x0eAddressService\x12E\n" +
	"\n" +
	"GetAddress\x12\x1a.address.GetAddressRequest\x1a\x1b.address.GetAddressResponse\x12T\n" +
	"\x0fValidateAddress\x12\x1f.address.ValidateAddressRequest\x1a .address.ValidateAddressResponse\x12Q\n" +
	"\x0eGeocodeAddress\x12\x1e.address.GeocodeAddressRequest\x1a\x1f.address.GeocodeAddressResponseB)Z'github.com/0xsj/fn-go/pkg/proto/addressb\x06proto3"

var (
	file_pkg_proto_address_address_proto_rawDescOnce sync.Once
	file_pkg_proto_address_address_proto_rawDescData []byte
)

func file_pkg_proto_address_address_proto_rawDescGZIP() []byte {
	file_pkg_proto_address_address_proto_rawDescOnce.Do(func() {
		file_pkg_proto_address_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_address_address_proto_rawDesc), len(file_pkg_proto_address_address_proto_rawDesc)))
	})
	return file_pkg_proto_address_address_proto_rawDescData
}

var file_pkg_proto_address_address_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_address_address_proto_goTypes = []any{
	(*Address)(nil),                 // 0: address.Address
	(*GetAddressRequest)(nil),       // 1: address.GetAddressRequest
	(*GetAddressResponse)(nil),      // 2: address.GetAddressResponse
	(*ValidateAddressRequest)(nil),  // 3: address.ValidateAddressRequest
	(*ValidateAddressResponse)(nil), // 4: address.ValidateAddressResponse
	(*GeocodeAddressRequest)(nil),   // 5: address.GeocodeAddressRequest
	(*GeocodeAddressResponse)(nil),  // 6: address.GeocodeAddressResponse
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}
var file_pkg_proto_address_address_proto_depIdxs = []int32{
	7, // 0: address.Address.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: address.Address.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: address.GetAddressResponse.address:type_name -> address.Address
	1, // 3: address.AddressService.GetAddress:input_type -> address.GetAddressRequest
	3, // 4: address.AddressService.ValidateAddress:input_type -> address.ValidateAddressRequest
	5, // 5: address.AddressService.GeocodeAddress:input_type -> address.GeocodeAddressRequest
	2, // 6: address.AddressService.GetAddress:output_type -> address.GetAddressResponse
	4, // 7: address.AddressService.ValidateAddress:output_type -> address.ValidateAddressResponse
	6, // 8: address.AddressService.GeocodeAddress:output_type -> address.GeocodeAddressResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_address_address_proto_init() }
func file_pkg_proto_address_address_proto_init() {
	if File_pkg_proto_address_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_address_address_proto_rawDesc), len(file_pkg_proto_address_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_address_address_proto_goTypes,
		DependencyIndexes: file_pkg_proto_address_address_proto_depIdxs,
		MessageInfos:      file_pkg_proto_address_address_proto_msgTypes,
	}.Build()
	File_pkg_proto_address_address_proto = out.File
	file_pkg_proto_address_address_proto_goTypes = nil
	file_pkg_proto_address_address_proto_depIdxs = nil
}
