// pkg/proto/incident/incident.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/incident/incident.proto

package incident

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Incident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	AddressId     string                 `protobuf:"bytes,4,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{0}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Incident) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Incident) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *Incident) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Incident) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Incident) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Incident) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Incident) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateIncidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	AddressId     string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncidentRequest) Reset() {
	*x = CreateIncidentRequest{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncidentRequest) ProtoMessage() {}

func (x *CreateIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncidentRequest.ProtoReflect.Descriptor instead.
func (*CreateIncidentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{1}
}

func (x *CreateIncidentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateIncidentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateIncidentRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *CreateIncidentRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateIncidentRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateIncidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incident      *Incident              `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIncidentResponse) Reset() {
	*x = CreateIncidentResponse{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIncidentResponse) ProtoMessage() {}

func (x *CreateIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIncidentResponse.ProtoReflect.Descriptor instead.
func (*CreateIncidentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIncidentResponse) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

type GetIncidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentRequest) Reset() {
	*x = GetIncidentRequest{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentRequest) ProtoMessage() {}

func (x *GetIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentRequest.ProtoReflect.Descriptor instead.
func (*GetIncidentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{3}
}

func (x *GetIncidentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetIncidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incident      *Incident              `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentResponse) Reset() {
	*x = GetIncidentResponse{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentResponse) ProtoMessage() {}

func (x *GetIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentResponse.ProtoReflect.Descriptor instead.
func (*GetIncidentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{4}
}

func (x *GetIncidentResponse) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

type UpdateIncidentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentRequest) Reset() {
	*x = UpdateIncidentRequest{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentRequest) ProtoMessage() {}

func (x *UpdateIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentRequest.ProtoReflect.Descriptor instead.
func (*UpdateIncidentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateIncidentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIncidentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateIncidentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateIncidentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateIncidentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incident      *Incident              `protobuf:"bytes,1,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentResponse) Reset() {
	*x = UpdateIncidentResponse{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentResponse) ProtoMessage() {}

func (x *UpdateIncidentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentResponse.ProtoReflect.Descriptor instead.
func (*UpdateIncidentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateIncidentResponse) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

type ListIncidentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentsRequest) Reset() {
	*x = ListIncidentsRequest{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentsRequest) ProtoMessage() {}

func (x *ListIncidentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentsRequest.ProtoReflect.Descriptor instead.
func (*ListIncidentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{7}
}

func (x *ListIncidentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListIncidentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListIncidentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListIncidentsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListIncidentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incidents     []*Incident            `protobuf:"bytes,1,rep,name=incidents,proto3" json:"incidents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIncidentsResponse) Reset() {
	*x = ListIncidentsResponse{}
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIncidentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIncidentsResponse) ProtoMessage() {}

func (x *ListIncidentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_incident_incident_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIncidentsResponse.ProtoReflect.Descriptor instead.
func (*ListIncidentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_incident_incident_proto_rawDescGZIP(), []int{8}
}

func (x *ListIncidentsResponse) GetIncidents() []*Incident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

func (x *ListIncidentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_pkg_proto_incident_incident_proto protoreflect.FileDescriptor

const file_pkg_proto_incident_incident_proto_rawDesc = "" +
	"\n" +
	"!pkg/proto/incident/incident.proto\x12\bincident\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x02\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"address_id\x18\x04 \x01(\tR\taddressId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa1\x01\n" +
	"\x15CreateIncidentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\"H\n" +
	"\x16CreateIncidentResponse\x12.\n" +
	"\bincident\x18\x01 \x01(\v2\x12.incident.IncidentR\bincident\"$\n" +
	"\x12GetIncidentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x13GetIncidentResponse\x12.\n" +
	"\bincident\x18\x01 \x01(\v2\x12.incident.IncidentR\bincident\"w\n" +
	"\x15UpdateIncidentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"H\n" +
	"\x16UpdateIncidentResponse\x12.\n" +
	"\bincident\x18\x01 \x01(\v2\x12.incident.IncidentR\bincident\"s\n" +
	"\x14ListIncidentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"_\n" +
	"\x15ListIncidentsResponse\x120\n" +
	"\tincidents\x18\x01 \x03(\v2\x12.incident.IncidentR\tincidents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xd9\x02\n" +
	"\x0fIncidentService\x12S\n" +
	"\x0eCreateIncident\x12\x1f.incident.CreateIncidentRequest\x1a .incident.CreateIncidentResponse\x12J\n" +
	"\vGetIncident\x12\x1c.incident.GetIncidentRequest\x1a\x1d.incident.GetIncidentResponse\x12S\n" +
	"\x0eUpdateIncident\x12\x1f.incident.UpdateIncidentRequest\x1a .incident.UpdateIncidentResponse\x12P\n" +
	"\rListIncidents\x12\x1e.incident.ListIncidentsRequest\x1a\x1f.incident.ListIncidentsResponseB*Z(github.com/0xsj/fn-go/pkg/proto/incidentb\x06proto3"

var (
	file_pkg_proto_incident_incident_proto_rawDescOnce sync.Once
	file_pkg_proto_incident_incident_proto_rawDescData []byte
)

func file_pkg_proto_incident_incident_proto_rawDescGZIP() []byte {
	file_pkg_proto_incident_incident_proto_rawDescOnce.Do(func() {
		file_pkg_proto_incident_incident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_incident_incident_proto_rawDesc), len(file_pkg_proto_incident_incident_proto_rawDesc)))
	})
	return file_pkg_proto_incident_incident_proto_rawDescData
}

var file_pkg_proto_incident_incident_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_incident_incident_proto_goTypes = []any{
	(*Incident)(nil),               // 0: incident.Incident
	(*CreateIncidentRequest)(nil),  // 1: incident.CreateIncidentRequest
	(*CreateIncidentResponse)(nil), // 2: incident.CreateIncidentResponse
	(*GetIncidentRequest)(nil),     // 3: incident.GetIncidentRequest
	(*GetIncidentResponse)(nil),    // 4: incident.GetIncidentResponse
	(*UpdateIncidentRequest)(nil),  // 5: incident.UpdateIncidentRequest
	(*UpdateIncidentResponse)(nil), // 6: incident.UpdateIncidentResponse
	(*ListIncidentsRequest)(nil),   // 7: incident.ListIncidentsRequest
	(*ListIncidentsResponse)(nil),  // 8: incident.ListIncidentsResponse
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
}
var file_pkg_proto_incident_incident_proto_depIdxs = []int32{
	9,  // 0: incident.Incident.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: incident.Incident.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: incident.CreateIncidentResponse.incident:type_name -> incident.Incident
	0,  // 3: incident.GetIncidentResponse.incident:type_name -> incident.Incident
	0,  // 4: incident.UpdateIncidentResponse.incident:type_name -> incident.Incident
	0,  // 5: incident.ListIncidentsResponse.incidents:type_name -> incident.Incident
	1,  // 6: incident.IncidentService.CreateIncident:input_type -> incident.CreateIncidentRequest
	3,  // 7: incident.IncidentService.GetIncident:input_type -> incident.GetIncidentRequest
	5,  // 8: incident.IncidentService.UpdateIncident:input_type -> incident.UpdateIncidentRequest
	7,  // 9: incident.IncidentService.ListIncidents:input_type -> incident.ListIncidentsRequest
	2,  // 10: incident.IncidentService.CreateIncident:output_type -> incident.CreateIncidentResponse
	4,  // 11: incident.IncidentService.GetIncident:output_type -> incident.GetIncidentResponse
	6,  // 12: incident.IncidentService.UpdateIncident:output_type -> incident.UpdateIncidentResponse
	8,  // 13: incident.IncidentService.ListIncidents:output_type -> incident.ListIncidentsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_proto_incident_incident_proto_init() }
func file_pkg_proto_incident_incident_proto_init() {
	if File_pkg_proto_incident_incident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_incident_incident_proto_rawDesc), len(file_pkg_proto_incident_incident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_incident_incident_proto_goTypes,
		DependencyIndexes: file_pkg_proto_incident_incident_proto_depIdxs,
		MessageInfos:      file_pkg_proto_incident_incident_proto_msgTypes,
	}.Build()
	File_pkg_proto_incident_incident_proto = out.File
	file_pkg_proto_incident_incident_proto_goTypes = nil
	file_pkg_proto_incident_incident_proto_depIdxs = nil
}
