name: CI

on:
  push:
    branches-ignore:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: npm
        run: NODE_OPTIONS=--openssl-legacy-provider npm install --legacy-peer-deps
      
      - name: Typescript 
        run: |
          npm run lint 
          npm run compile